backend/base/api/urls.py
from django.urls import path
from . import views
from rest_framework_simplejwt.views import (
    TokenRefreshView,
)
from .views import MyTokenObtainPairView


urlpatterns = [
    
    path('token/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    
    
    path('', views.home,name="HOME"),
    # Rooms Routing
    path('GetRooms/', views.GetRooms,name="GetRooms"),
    path('GetRoomsByUserID/<int:pk>', views.GetRoomsByUserID,name="GetRoomsByUserID"),
    path('GetRoomsByTopicID/<int:pk>', views.GetRoomsByTopicID,name="GetRoomsByTopicID"),
    path('GetRoomsByTitleName/<str:pk>', views.GetRoomsByTitleName,name="GetRoomsByTitleName"),

    path('GetRoom/<str:pk>', views.GetRoom,name="GetRoom"),
    path('CreateRoom/', views.CreateRoom,name="CreateRoom"),
    path('UpdateRoom/<str:pk>', views.UpdateRoom,name="UpdateRoom"),
    path('DeleteRoom/<str:pk>', views.DeleteRoom,name="DeleteRoom"),
    # Topics Routing
    path('GetTopics/', views.Topics,name="GetTopics"),
    path('GetTopic/<int:pk>', views.Topics,name="GetTopic"),
    path('SearchTopics/<str:pk>', views.SearchTopics,name="SearchTopics"),
    path('CreateTopic/', views.CreateTopic,name="CreateTopic"),
    path('UpdateTopic/<str:pk>', views.UpdateTopic,name="UpdateTopic"),
    # Messages Routing
    path('GetMessages/', views.GetMessages,name="GetMessages"),
    path('GetMessages/<str:pk>', views.GetSMessages,name="GetSMessages"),
    path('GetMessageByID/<int:pk>', views.GetMessageByID,name="GetMessageByID"),
    path('GetMessagesByRoomID/<int:pk>', views.GetMessagesByRoomID,name="GetMessagesByRoomID"),
    path('GetMessagesByUserID/<int:pk>', views.GetMessagesByUserID,name="GetMessagesByUserID"),
    path('GetMessagesByTopicID/<int:pk>', views.GetMessagesByTopicID,name="GetMessagesByTopicID"),    
    
    path('CreateMessage/', views.CreateMessage,name="CreateMessage"),
    path('DeleteMessage/<str:pk>', views.DeleteMessage,name="DeleteMessage"),
    # User Routing
    path('GetUserProfile/<str:pk>', views.GetUserProfile,name="GetUserProfile"),
    path('UpdateUserProfile/<int:pk>', views.UpdateUserProfile,name="UpdateUserProfile"),
    path('CreateUserProfilea', views.CreateUserProfile,name="CreateUserProfile"),
    #Activities
    
    

    
    
    
    
]

backend/base/urls.py
from django.contrib import admin
from django.urls import path
from . import views
urlpatterns = [
    path('', views.home,name="home"),
    path('login/', views.loginPage,name="login"),
    path('register/', views.RegisterPage,name="register"),
    path('logout/', views.logoutPage,name="logout"),
    path('room/<str:pk>/', views.room,name="room"),
    path('profile/<str:pk>/', views.user_profile,name="user-profile"),
    path('setting/', views.userSetting,name="update-user"),
    path('create-room/', views.createroom,name="create-room"),
    path('update-room/<str:pk>/',views.updateRoom,name="update-room"),
    path('delete-room/<str:pk>/',views.deleteRoom,name="delete-room"),
    path('delete-message/<str:pk>/',views.deleteMessage,name="delete-message"),
    path('browse-topics/',views.browseTopics,name="browse-topics"),
    path('activity-feed/',views.activityFeed,name="activity-feed"),
    
]

backend/studybud/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('view/', include('base.urls')),
    path('', include('base.api.urls')),
    
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

backend/base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    name=models.CharField(max_length=200,null=True)
    email=models.EmailField(unique=True)
    bio=models.TextField(null=True)
    avatar=models.ImageField(null=True,default="avatar.svg")
    
    USERNAME_FIELD='email'
    REQUIRED_FIELDS=[]

# Create your models here.
class Topic(models.Model):
    name=models.CharField(max_length=200)
    
    def __str__(self):
        return self.name

class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(User, related_name='participants', blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-updated', '-created']
        unique_together = ['name', 'topic']
        
    def __str__(self):
        return self.name
    
    
class Message(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    room=models.ForeignKey(Room, on_delete=models.CASCADE)
    body=models.TextField()
    updated=models.DateTimeField(auto_now=True)
    created=models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering=['-created','-updated']
    
    def __str__(self):
        return self.body[0:50]

backend/base/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from .models import Room,User


class MyUserCreationForm(UserCreationForm):
    class Meta:
        model=User
        fields=['name','username','email','password1','password2']


class RoomForm(ModelForm):
    class Meta:
        model=Room
        fields='__all__'
        exclude=['host','participants']
        
        
class UserForm(ModelForm):
    class Meta:
        model=User
        fields=['avatar','name','username','email','bio']

backend/base/api/views.py
from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from base.models import Room,Topic,Message,User
from .serializers import RoomSerializer,RoomCreateSerializer,UserUpdateProfileSerializer,CreateUserProfileSerializer,TopicSerializer,RoomSerializerWithParticipants,MessageSerializer,UserProfileSerializer,CreateMessageSerializer
from rest_framework.exceptions import PermissionDenied
from rest_framework_simplejwt.serializers import TokenObtainPairSerializer
from rest_framework_simplejwt.views import TokenObtainPairView
from rest_framework_simplejwt.authentication import JWTAuthentication
from rest_framework.permissions import IsAuthenticated
from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.db import IntegrityError

class MyTokenObtainPairSerializer(TokenObtainPairSerializer):
    @classmethod
    def get_token(cls, user):
        token = super().get_token(user)

        # Add custom claims
        # token['email'] = user.email
        # ...

        return token
    
    def validate(self, attrs):
            data = super().validate(attrs)
    
            user = self.user
            data["user_id"] = user.id
            data["username"] = user.username
            data["email"] = user.email
            # ... add other user information as needed
    
            return data


class MyTokenObtainPairView(TokenObtainPairView):
    serializer_class=MyTokenObtainPairSerializer





@api_view(['GET'])
def home(request):
    routes=[
        'GET /GetRooms',
        'GET /GetRoomsByUserID/int:pk',
        'GET /GetRoomsByTopicID/int:pk',        
        'GET /GetRoomsByTitleName/str:pk',
        'GET /GetRoom/int:pk',
        'GET /CreateRoom',
        'GET /UpdateRoom/int:pk',
        'GET /DeleteRoom/int:pk',
        'GET /GetTopics',
        'GET /GetTopic/int:pk',
        'GET /SearchTopics/str:pk',
        'GET /CreateTopic',
        'GET /UpdateTopic/int:pk',
        'GET /GetMessages',
        'GET /GetMessageByID/int:pk',        
        'GET /GetMessages/str:pk',
        'GET /GetMessagesByRoomID/int:pk',
        'GET /GetMessagesByUserID/int:pk',
        'GET /GetMessagesByTopicID/int:pk',        
        'GET /CreateMessage',
        'GET /DeleteMessage/int:pk',
        'GET /GetUserProfile/int:pk',
        'GET /UpdateUserProfile/int:pk',
        'POST /CreateUserProfilea',
        
    ]
    return Response(routes)


# User Modal EndPoints
@api_view(['GET'])
def GetUserProfile(request,pk):
    user = User.objects.get(id=pk)
    serializer = UserProfileSerializer(user, many=False)
    return Response(serializer.data)


@api_view(['POST'])
@permission_classes([IsAuthenticated])
def CreateUserProfile(request):
    print(request.data)
    serializer = CreateUserProfileSerializer(data=request.data)
    if serializer.is_valid():
        serializer.save()
        return Response(serializer.data, status=200)

    return Response(serializer.errors, status=400)


@api_view(['PUT'])
@permission_classes([IsAuthenticated])
def UpdateUserProfile(request,pk):
    user = User.objects.get(id=pk)
    if user != request.user:
        raise PermissionDenied("You can't edit this profile.")
    else:
        serializer = UserUpdateProfileSerializer(instance=user, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=200)

    return Response(serializer.errors, status=400)


    
@api_view(['GET'])
def TokenAuth(request):
    token = request.headers.get('Authorization', None)
    print("Received token:", token)
    jwt_authenticator = JWTAuthentication()
    authentication_result = jwt_authenticator.authenticate(request)

    if authentication_result is not None:
        user, token = authentication_result
        token_claims = token.payload
        print("Decoded token claims:", token_claims)
        return Response({"message": "Done"}, status=201)
    else:
        print("No valid token found in the header")
        return Response({"error": "No valid token found in the header."}, status=401)



# CRUD FOR ROOMS CLASS
@api_view(['GET'])
def GetRooms(request):
    rooms = Room.objects.all()

    serializer = RoomSerializer(rooms, many=True)
    return Response(serializer.data)

@api_view(['GET'])
def GetRoomsByUserID(request,pk):
    rooms = Room.objects.filter(Q(host__id=pk))

    serializer = RoomSerializer(rooms, many=True)
    return Response(serializer.data)

@api_view(['GET'])
def GetRoomsByTopicID(request,pk):
    rooms = Room.objects.filter(Q(topic__id=pk))

    serializer = RoomSerializer(rooms, many=True)
    return Response(serializer.data)


@api_view(['GET'])
def GetRoomsByTitleName(request, pk):
    rooms = Room.objects.filter(Q(name__icontains=pk))
    serializer = RoomSerializer(rooms, many=True)
    return Response(serializer.data)




@api_view(['GET'])
def GetRoom(request, pk=None):
    rooms = Room.objects.get(id=pk)
    serializer = RoomSerializerWithParticipants(rooms, many=False)
    return Response(serializer.data)

# RoomCreateSerializer



@api_view(['POST'])
@permission_classes([IsAuthenticated])
def CreateRoom(request):
    data = request.data.copy()

    # Handle Topic creation or retrieval based on the topic name
    topic_name = data.get('topic', '')
    topic, created = Topic.objects.get_or_create(name=topic_name)
    data['topic'] = topic.id  # Assigning the ID of the topic

    serializer = RoomSerializer(data=data)

    if serializer.is_valid():
        try:
            room = serializer.save(host=request.user, topic=topic)  # Directly save with host and topic
            return Response("Room created successfully.", status=201)
        except IntegrityError:
            # Handle the unique constraint violation
            return Response("A room with this name and topic already exists.", status=400)
    
    return Response(serializer.errors, status=400)

   



# @api_view(['POST'])
# @permission_classes([IsAuthenticated])
# def CreateRoom(request):
    
#     data = request.data.copy()
#     data['host'] = request.user.id
#     serializer = RoomSerializer(data=data)

#     if serializer.is_valid():
#         serializer.save()
#         return Response(serializer.data, status=201)
    
#     return Response(serializer.errors, status=400)

@api_view(['PUT'])
@permission_classes([IsAuthenticated])
def UpdateRoom(request, pk):
    try:
        room = Room.objects.get(id=pk)
    except Room.DoesNotExist:
        return Response({'error': 'Room not found.'}, status=404)

    if room.host != request.user:
        raise PermissionDenied("You are not the host of this room.")

    serializer = RoomSerializer(instance=room, data=request.data)

    if serializer.is_valid():
        serializer.save()
        return Response(serializer.data, status=200)

    return Response(serializer.errors, status=400)


@api_view(['DELETE'])
@permission_classes([IsAuthenticated])
def DeleteRoom(request, pk):
    try:
        room = Room.objects.get(id=pk)
    except Room.DoesNotExist:
        return Response({'error': 'Room not found.'}, status=404)

    if room.host != request.user:
        raise PermissionDenied("You are not the host of this room.")

    room.delete()
    
    return Response({'message': 'Room deleted successfully'}, status=204)



#CRUD FOR TOPICS
@api_view(['GET'])
def Topics(request, pk=None):
    if pk is None:
        topics = Topic.objects.all()
    else:
        topics = Topic.objects.filter(id=pk)
    serializer = TopicSerializer(topics, many=True)
    return Response(serializer.data)

@api_view(['GET'])
def SearchTopics(request, pk):
    topics = Topic.objects.filter(Q(name__icontains=pk))
    serializer = TopicSerializer(topics, many=True)
    return Response(serializer.data)


@api_view(['POST'])
def CreateTopic(request):
    
    data = request.data.copy()
    serializer = TopicSerializer(data=data)

    if serializer.is_valid():
        serializer.save()
        return Response(serializer.data, status=201)
    
    return Response(serializer.errors, status=400)




@api_view(['PUT'])
def UpdateTopic(request, pk):
    try:
        topic = Topic.objects.get(id=pk)
    except Topic.DoesNotExist:
        return Response({'error': 'Topic not found.'}, status=404)

    serializer = TopicSerializer(instance=topic, data=request.data)

    if serializer.is_valid():
        serializer.save()
        return Response(serializer.data, status=200)

    return Response(serializer.errors, status=400)


# Messages
@api_view(['GET'])
def GetMessages(request):
    rooms = Message.objects.all().order_by('-created')[:5]
    serializer = MessageSerializer(rooms, many=True)
    return Response(serializer.data)

# Messages
@api_view(['GET'])
def GetSMessages(request, pk):
    messages = Message.objects.filter(Q(room__name__icontains=pk)).order_by('-created')[:5]
    serializer = MessageSerializer(messages, many=True)
    return Response(serializer.data)


@api_view(['GET'])
def GetMessageByID(request, pk):
    messages = Message.objects.get(id=pk)
    serializer = MessageSerializer(messages, many=False)
    return Response(serializer.data)

@api_view(['GET'])
def GetMessagesByRoomID(request, pk):
    messages = Message.objects.filter(Q(room__id=pk))
    serializer = MessageSerializer(messages, many=True)
    return Response(serializer.data)

@api_view(['GET'])
def GetMessagesByUserID(request, pk):
    messages = Message.objects.filter(Q(user__id=pk)).order_by('-created')[:25]
    serializer = MessageSerializer(messages, many=True)
    return Response(serializer.data)

@api_view(['GET'])
def GetMessagesByTopicID(request, pk):
    messages = Message.objects.filter(Q(room__topic=pk)).order_by('-created')[:5]
    serializer = MessageSerializer(messages, many=True)
    return Response(serializer.data)





@api_view(['POST'])
@permission_classes([IsAuthenticated])
def CreateMessage(request):
    data = request.data.copy()

backend/base/templates/base/activity_comp.html
<div class="activities">
  <div class="activities__header">
    <h2>Recent Activities</h2>
  </div>
  {% for value in room_messages %}
  <div class="activities__box">
    <div class="activities__boxHeader roomListRoom__header">
      <a
        href="{% url 'user-profile' value.user.id %}"
        class="roomListRoom__author"
      >
        <div class="avatar avatar--small">
          <img src="{{value.user.avatar.url}}" />
        </div>
        <p>
          @{{value.user}}
          <span>{{value.created|timesince}} ago</span>
        </p>
      </a>
      {% if request.user == value.user %}
      <div class="roomListRoom__actions">
        <a href="{% url 'delete-message' value.id %}">
          <svg
            version="1.1"
            xmlns="http://www.w3.org/2000/svg"
            width="32"
            height="32"
            viewBox="0 0 32 32"
          >
            <title>remove</title>
            <path
              d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
            ></path>
          </svg>
        </a>
      </div>
      {% endif %}
    </div>
    <div class="activities__boxContent">
      <p>
        replied to post “<a href="{% url 'room' value.room.id %}"
          >{{value.room}}</a
        >”
      </p>
      <div class="activities__boxRoomContent">{{value}}</div>
    </div>
  </div>
  {% endfor %}
</div>

backend/base/templates/base/delete_old.html
{% extends 'main.html' %} {% block Content %}
<form method="POST">
  {% csrf_token %}
  <p>Are you sure to delete "{{obj.name}}"?</p>
  <a href="{{request.META.HTTP_REFERER}}">Go Back</a>
  <input type="submit" value="Confirm" />
</form>
{% endblock Content %}

backend/base/templates/base/feed_comp.html
{% for room in data %}
<div class="roomListRoom">
    <div class="roomListRoom__header">
      <a href="{% url 'user-profile' room.host.id %}" class="roomListRoom__author">
        <div class="avatar avatar--small">
          <img src="{{room.host.avatar.url}}" />
        </div>
        <span>@{{room.host.username}}</span>
      </a>
      <div class="roomListRoom__actions">
        <span>{{room.created|timesince}} ago</span>
      </div>
    </div>
    <div class="roomListRoom__content">
      <a href="{% url 'room' room.id %}">{{room.name}}</a>
      <p>
        {{room.description}}
      </p>
    </div>
    <div class="roomListRoom__meta">
      <a href="{% url 'room' room.id %}" class="roomListRoom__joined">
        <svg
          version="1.1"
          xmlns="http://www.w3.org/2000/svg"
          width="32"
          height="32"
          viewBox="0 0 32 32"
        >
          <title>user-group</title>
          <path
            d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z"
          ></path>
          <path
            d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z"
          ></path>
          <path
            d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z"
          ></path>
          <path
            d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z"
          ></path>
        </svg>
        {{room.participants.all.count}} Joined
      </a>
      <p class="roomListRoom__topic">{{room.topic.name}}</p>
    </div>
  </div>
  {% endfor %}

{% comment %} 
{% for room in data %}
    <p style="cursor: pointer; color: blue">
    {% if request.user == room.host %}
    <a href="{% url 'update-room' room.id %}">Edit</a><br>
    <a href="{% url 'delete-room' room.id %}">Delete</a><br>
    {% endif %}
    <a href="{% url 'user-profile' room.host.id %}">@{{room.host.username}}</a><br />
    <a href="{% url 'room' room.id %}" target="_blank">{{room.name}}</a><br />
    <small>{{room.topic.name}}</small>
    <hr>
    </p>
{% endfor %} {% endcomment %}

backend/base/templates/base/home.html
{% extends 'main.html' %} {% block Content %}
<main class="layout layout--3">
  <div class="container">
    <!-- Topics Start -->

    <!-- Topics End -->
    {% include 'base/topic_comp.html' %}
    <!-- Room List Start -->
    <div class="roomList">
      <div class="mobile-menu">
        <form method="GET" action="{% url 'home' %}" class="header__search">
          <label>
            <svg
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 32 32"
            >
              <title>search</title>
              <path
                d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
              ></path>
            </svg>
            <input type="text" name="q" placeholder="Search for rooms...." />
          </label>
        </form>
        <div class="mobile-menuItems">
          <a class="btn btn--main btn--pill" href="{% url 'browse-topics' %}"
            >Browse Topics</a
          >
          <a class="btn btn--main btn--pill" href="{% url 'activity-feed' %}"
            >Recent Activities</a
          >
        </div>
      </div>
      <div class="roomList__header">
        <div>
          <h2>Study Room</h2>
          <p>{{room_count}} Rooms available</p>
        </div>
        <a class="btn btn--main" href="{% url 'create-room' %}">
          <svg
            version="1.1"
            xmlns="http://www.w3.org/2000/svg"
            width="32"
            height="32"
            viewBox="0 0 32 32"
          >
            <title>add</title>
            <path
              d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
            ></path>
          </svg>
          Create Room
        </a>
      </div>
      {% include 'base/feed_comp.html' %}
    </div>
    <!-- Room List End -->

    <!-- Activities Start -->
    {% include 'base/activity_comp.html' %}
    <!-- Activities End -->
  </div>
</main>
{% endblock Content %}

backend/base/templates/base/home_old.html
{% extends 'main.html' %} {% block Content %}
<style>
  .home-container {
    display: grid;
    grid-template-columns: 1fr 3fr 1fr;
  }
</style>
<div class="home-container">
  <div>{% include 'base/topic_comp.html' %}</div>
  <div>
    <h5>{{room_count}} rooms available</h5>
    <a href="{% url 'create-room' %}">Create Room</a>
    {% include 'base/feed_comp.html' %}
  </div>
  <div>{% include 'base/activity_comp.html' %}</div>
</div>
{% endblock Content %}

backend/base/templates/base/login_register_old.html
{% extends 'main.html' %} {% block Content %} {% if page == 'login' %}
<div>
  <form method="POST" action="">
    {% csrf_token %}
    <label>Username:</label>
    <input type="text" name="username" />
    <label>Password:</label>
    <input type="Password" name="password" />
    <input type="submit" value="Login" />
  </form>
  <p>Haven't signed up yet?</p>
  <a href="{% url 'register' %}">Sign up</a>
</div>
{% else %}
<div>
  <form method="POST" action="">
    {% csrf_token %} {{form.as_p}}
    <input type="submit" value="Register" />
  </form>
  <p>Already signed up?</p>
  <a href="{% url 'login' %}">Login</a>
</div>
{% endif %} {% endblock Content %}

backend/base/templates/base/profile_old.html
{% extends 'main.html' %} {% block Content %}
<style>
  .profile-container {
    display: grid;
    grid-template-columns: 1fr 3fr 1fr;
  }
</style>
<div class="profile-container">
  <div>{% include 'base/topic_comp.html' %}</div>
  <div>
    <h1>{{user.username}}</h1>
    {% include 'base/feed_comp.html' %}
  </div>
  <div>{% include 'base/activity_comp.html' %}</div>
</div>
{% endblock Content %}

backend/base/templates/base/room_form_old.html
{% extends 'main.html' %} {% block Content %}
<div>
  <form method="POST" action="">
    {% csrf_token %} {{form.as_p}}
    <input type="submit" value="Submit" />
  </form>
</div>
{% endblock Content %}

backend/base/templates/base/topic_comp.html
<div class="topics">
  <div class="topics__header">
    <h2>Browse Topics</h2>
  </div>
  <ul class="topics__list">
    <li>
      <a href="{% url 'home' %}" class="active"
        >All <span>{{topic.count}}</span></a
      >
    </li>
    {% for value in topic %}
    <li>
      <a href="{% url 'home' %}?q={{value.name}}"
        >{{value.name}}<span>{{value.room_set.all.count}}</span></a
      >
    </li>
    {% endfor %}
  </ul>
  <a class="btn btn--link" href="{% url 'browse-topics' %}">
    More
    <svg
      version="1.1"
      xmlns="http://www.w3.org/2000/svg"
      width="32"
      height="32"
      viewBox="0 0 32 32"
    >
      <title>chevron-down</title>
      <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
    </svg>
  </a>
</div>

backend/base/templates/base/topics.html
{% extends 'main.html' %} {% block Content %}
<main class="create-room layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{% url 'home' %}">
            <svg
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 32 32"
            >
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
              ></path>
            </svg>
          </a>
          <h3>Browse Topics</h3>
        </div>
      </div>

      <div class="topics-page layout__body">
        <form method="GET" action="" class="header__search">
          <label>
            <svg
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 32 32"
            >
              <title>search</title>
              <path
                d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
              ></path>
            </svg>
            <input type="text" name="q" placeholder="Search for topics...." />
          </label>
        </form>

        <ul class="topics__list">
          <li>
            <a href="{% url 'browse-topics' %}" class="active"
              >All <span>{{topic.count}}</span></a
            >
          </li>
          {% for value in topic %}
          <li>
            <a href="{% url 'home' %}?q={{value.name}}"
              >{{value.name}}<span>{{value.room_set.all.count}}</span></a
            >
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</main>
{% endblock Content %}